### ISSUE TITLE
Getting error when adding DSN for MongoDB in MS Excel

### ISSUE THREAD

**Issue by sagar-gopale** [openlink/iODBC#101]
I am using
- MacOs Ventura version 13.3.1(a). 
- MS Excel version 16.78
- I have installed iODBC version 3.52.16 driver for MacOS Ventura from [https://www.iodbc.org/dataspace/doc/iodbc/wiki/iodbcWiki/Downloads](https://www.iodbc.org/dataspace/doc/iodbc/wiki/iodbcWiki/Downloads)
- I have tried this with local mongo server as well as remote Mongo cluster from Atlas.
- I am able to connect to the Mongo cluster using MongoAtlas client(To be sure that there are no network restrictions)
- The `mongosqld` utility is also running and it is able to sample schemas from MongoDB(as seen in logs).

Below is what my `mongosqld` config looks like for local mongodb connection.

```
## This is a example configuration file for mongosqld.

## The full documentation is available at:
## https://docs.mongodb.com/bi-connector/master/reference/mongosqld/#configuration-file

## Network options - configure how mongosqld should accept connections.
## https://docs.mongodb.com/bi-connector/master/reference/mongosqld/#network-options
net:
  bindIp: "127.0.0.1"
  port: 3307
  ssl:
    mode: "disabled"
mongodb:
  net:
    uri: "mongodb://localhost:27017" # https://docs.mongodb.com/manual/reference/connection-string/#mongodb-uri
    ssl:
      enabled: false

## Logging options
systemLog:
  path: './mongosql.log'
  quiet: false
  verbosity: 1
  logAppend: true
  logRotate: "reopen" # "rename"|"reopen"

## Schema options
schema:
  refreshIntervalSecs: 0
  stored:
    mode: "auto" # "auto"|"custom"
    source: "<myDatabase>" # the database where schemas are stored in stored-schema modes
    # name: "" # the named schema to read/write to in stored-schema modes
  sample:
    size: 1000 # The amount of random documents we sample from each collection.
    namespaces: ["*.*"]
processManagement:
  service:
    name: "mongosql"
    displayName: "MongoSQL Service"
    description: "MongoSQL accesses MongoDB data with SQL"
```

I am using below values when adding `System DSN` in MS Excel.
```
- SERVER=127.0.0.1
- PORT=3307
- DATABASE=<myDatabase>
- UID=<myUsername>?source=admin # In case of remote MongoDB Atlas cluster
- PWD=<myPwd> # In case of remote MongoDB Atlas cluster
```

I can see below drivers in MS Excel when adding System DSN. I have tried with both.

<img width="556" alt="Screenshot 2024-03-28 at 1 02 44 PM" src="https://github.com/openlink/iODBC/assets/134253186/eac0b77d-fb86-485a-a030-14bf5a81fbf0">

I get below error dialog when I try to create DSN.

<img width="643" alt="Screenshot 2024-03-28 at 1 04 00 PM" src="https://github.com/openlink/iODBC/assets/134253186/79beb3ea-5b51-448a-9164-01db604beb11">

I am not sure how to debug this. I have tried the solution at [https://github.com/openlink/iODBC/issues/34](https://github.com/openlink/iODBC/issues/34). Changing the permission of `odbcinst.ini` that is present in /Library/ODBC.
NOTE: I am the administrator on this system.
